name: Build kernel from pull request

on:
  pull_request:
    branches:
      - master
env:
  GCS_BUCKET: images.metal-pod.io

jobs:
  build:
    runs-on: ubuntu-22.04
 
    strategy:
      matrix:
        kernel: ["6.1.22"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Figure out if running fork PR
        id: fork
        run: '["${{ secrets.DOCKER_REGISTRY_TOKEN }}" == ""] && echo "::set-output name=is_fork_pr::true" || echo "::set-output name=is_fork_pr::false"'

      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          docker build --build-arg KERNEL_MAJOR="v6.x" \
                      --build-arg KERNEL_VERSION=${{ matrix.kernel }} \
                      --build-arg KERNEL_SERIES="mainline" \
                      --tag metal-stack/kernel .
          docker export $(docker create metal-stack/kernel /dev/null) > kernel.tar
          tar -xf kernel.tar metal-kernel
          cp metal-kernel metal-kernel-${{ matrix.kernel }}-pr-${GITHUB_HEAD_REF##*/}

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Upload kernel to GCS
        run: gsutil -m cp -r metal-kernel gs://$GCS_BUCKET/metal-kernel/pull_requests/metal-kernel-${{ matrix.kernel }}
        if: steps.fork.outputs.is_fork_pr == 'false'
