name: Build kernel from pull request

on:
  pull_request:
    branches:
      - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        kernel: ["5.10.3"]

    steps:
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Figure out if running fork PR
          id: fork
          run: '["${{ secrets.DOCKER_REGISTRY_TOKEN }}" == ""] && echo "::set-output name=is_fork_pr::true" || echo "::set-output name=is_fork_pr::false"'
    
        - name: Build project # This would actually build your project, using zip for an example artifact
          run: |
            docker build --build-arg KERNEL_MAJOR="v5.x" \
                        --build-arg KERNEL_VERSION=${{ matrix.kernel }} \
                        --build-arg KERNEL_SERIES="mainline" \
                        --tag metal-stack/kernel .
            docker export $(docker create metal-stack/kernel /dev/null) > kernel.tar
            tar -xf kernel.tar metal-kernel
            mv metal-kernel metal-kernel-${{ matrix.kernel }}-pr-${GITHUB_HEAD_REF##*/}

        - name: Upload
          id: upload-artifact
          uses: actions/upload-artifact@v2
          with:
            path: ./metal-kernel-${{ matrix.kernel }}-pr-${GITHUB_HEAD_REF##*/}
            name: metal-kernel
